### ISSUE TITLE
Subtitles

### ISSUE THREAD

**Issue by HenkeDahl** [emilsvennesson/kodi-cmore#15] opened 2018-02-08 23:09 UTC
Is it possible to use subtitles on the movies? It works fine in channels but not on movies.

**Comment by emilsvennesson** [comment] 2018-02-09 10:41
Hi!

Subtitles require Kodi 18 as stated in the README. I'm closing this because it is a duplicate of #9.

**Closed as completed by emilsvennesson** 2018-02-09 10:41 UTC
Labels: duplicate
